version: '3'
services:
  api:
    image: 'x.dkr.ecr.eu-north-1.amazonaws.com/api-test:IMAGE_TAG'
    links:
      - 'redis'
    ports:
      - 80:80
  redis:
    image: 'redis:alpine3.10'
    volumes:
      - '/var/app/current/redis-volume:/var/lib/redis/data'
